### ISSUE TITLE
Add support for selecting the highres sampler

### ISSUE THREAD

**Issue by skfoo** [mcmonkeyprojects/sd-infinity-grid-generator-script#118]
The Automatic UI lets you use a different sampler for the upscale pass than the original pass; please add support for doing that in the grid files too.

Basically put a line like the following somewhere in infinity_grid.py where you see fit:

`registerMode("HighRes Sampler", GridSettingMode(dry=True, type="text", apply=apply_field("hr_sampler_name"), valid_list=lambda: list(sd_samplers.all_samplers_map.keys())))
`

**Comment by mcmonkey4eva** [comment]
added, and hr model too
