### ISSUE TITLE
Save the hidden axis values set in Advanced Settings across page reloads

### ISSUE THREAD

**Issue by skfoo** [mcmonkeyprojects/sd-infinity-grid-generator-script#121]
The web page currently saves the x/y/super axis values in the location hash, but not which axis values are hidden. So if you turned off a bunch of axis values and then reload the page, you have to go to advanced settings and turn them off again.

I made a PR that saves the hidden values in the location hash.

**Comment by mcmonkey4eva** [comment]
Hi, uh, a lot of that PR #120  was complex scaffolding for the new feature, so I simplified it down to just a few blocks. Works the same in my testing.

Thank you for all the contributions btw! Very much appreciated!

**Comment by skfoo** [comment]
You're welcome :) 

There's two reasons why the code was the way it was,

1. Separation by single use responsibility. If you have two devs on the team and one works on how the information is saved (read/write to url hash) and another works on what needs to be saved (ie they work on user-visible features), the two devs can work on their thing without conflicts because they're separate functions. One dev can save/restore whatever features they need to support, and the other dev can change/improve/migrate the code that saves and restores any state. With the way it is now, it's more compact but you if you change **how** it's recorded you're also modifying the code that's responsible for **what** gets recorded — it's the same lines of code. But it's your codebase and you're responsible for it all, so that's fine :D

2. How can I implement this reliably while waiting for my grid to generate?

I like using a set table and queue table classes (a dictionary where the values are sets or arrays), so a large chunk of that PR would have collapsed to a few lines. I didn't have that here but wanted to use the technique so it resulted in ugly fat functions.
