### ISSUE TITLE
How to express square brackets in configuration YAML?

### ISSUE THREAD

**Issue by greasyi** [mcmonkeyprojects/sd-infinity-grid-generator-script#124]
I wanted to try e.g. `[dog:cat:0.5]` in a value for a "Prompt" axis, but square brackets denote lists in YAML.
I tried escaping with `\[dog:cat:0.5\]` but the backslashes made it into the final prompt, which caused the prompt to "fail".

Is this a feature request, or is there already a way to accomplish this that I don't know about?

**Comment by mcmonkey4eva** [comment]
Just "quote" the whole line, eg:
```yml
    prompt: "some [prompt] here"
````
