### ISSUE TITLE
Prompt Replacement: Replace Entire comma'ed Phrase with ""--works in xyz plot!

### ISSUE THREAD

**Issue by rafstahelin** [mcmonkeyprojects/sd-infinity-grid-generator-script#129]
The S/R method in xyz plot native script allows me to run an entire string containing "comma's", as long as the string is contained in " " and a comma. 

Here's an example:
"natural photo of t1k0 woman, closeup, wet hair, bikini top, standing in bedroom, glass door, pool in background, toys, books, mirror, fisheye wideangle lens, high fidelity,  small breasts, portrait, zoom, masterpiece","photo of t1k0 woman, fisheye portrait from low angle, in a amazon jungle, bodycon, bikini, sexy, jewellery"

Unusual, but proven to work in Forge xyz plot. 

Errors though in Infinite Grid. Is there a code to change to allow this behavior to work?

thanks

**Comment by mcmonkey4eva** [comment]
In infinite grid generator and swarm, use `||` to separate text that contains commas, which was added for precisely this reason (and intended to be a bit less of a mess than the old x/y plot script using a csv parser)

**Comment by rafstahelin** [comment]
My bad. Didn't read the whole thing!! Thanks.
