### ISSUE TITLE
Error using Symlink for Output file: {"detail":"File not allowed: E:/studio Dropbox/studio/ai...

### ISSUE THREAD

**Issue by rafstahelin** [mcmonkeyprojects/sd-infinity-grid-generator-script#138]
## Output Issue
```
{"detail":"File not allowed: E:/studio Dropbox/studio/ai
```

I use a **symlink** to send my output to my dropbox. 

I am getting this error when follow the output link. 

### Or a way to be able to use the symlink? Love this extensions, but i have a system with dropbox via symlink to get everything backed all the time
thanks

![image](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/assets/64715158/d8a98597-8ec8-4f48-aad3-545da36d1911)

**Comment by mcmonkey4eva** [comment]
This error didn't come from infinity-grid -- possibly upstream blockage in auto webui?
Last I tried things (been a few months tbh) symlinks worked fine -- all my output dirs for auto webui were always symlinked, so I was the first one to complain anytime they broke. It's possible a recent webui change broke symlink support?

**Comment by rafstahelin** [comment]
Hey, thanks for coming back to me

The symlinks work fine in general. I just get this message with the
extension

Umm

I could dig a little deeper
Maybe ask forge people and see if there isn’t a different cause at work
even if it only happens with infinite grid

thanks

**Comment by rafstahelin** [comment]
> {"detail":"File not allowed: E:/studio Dropbox/studio/ai

Looks like it doesnt like the grid output path to be outside of the webui root. So i guess I'll have to keep grids in the webui->ouput folder
