### ISSUE TITLE
Long Prompts: A way to store and call on them avoiding the temporary nature of the prompt field in Infinity Grid

### ISSUE THREAD

**Issue by rafstahelin** [mcmonkeyprojects/sd-infinity-grid-generator-script#139]
@mcmonkey4eva 

hello again. 

just wondering if there is a way to use csv or wildcard files to test large prompts, which are cumbersome to paste into the prompt field. Just imagine if i am testing for 10x prompts. It gets messy

Could I use some form of file to link to the field?

**Comment by mcmonkey4eva** [comment]
You can use yaml files to define your grids more conveniently for complex inputs, there's a guide in the readme and several samples in the assets folder.

**Comment by rafstahelin** [comment]
That’s true I will pursue that Thanks On 29 Apr 2024, at 23:06, mcmonkey4eva ***@***.***> wrote:﻿
You can use yaml files to define your grids more conveniently for complex inputs, there's a guide in the readme and several samples in the assets folder.

**Comment by rafstahelin** [comment]
> You can use yaml files to define your grids more conveniently for complex inputs, there's a guide in the readme and several samples in the assets folder.

been learning about the yaml. it's a great way to xy plot. so useful!
