### ISSUE TITLE
easy way to iterate axis: Model by replacing the "steps" incrementally

### ISSUE THREAD

**Issue by rafstahelin** [mcmonkeyprojects/sd-infinity-grid-generator-script#140]
I am xy plotting for checkpoint trainings. 

A typical Model looks like this:

modelname-step00001000.safetensors

So in Axis Model I have to put:

           Model: modelname-step00001000, modelname-step00001200, modelname-step00001400, and so on

I wonder if there is a simple way to not have to write the whole model name for every value. My model names are quite long:
gr4ph1cwbw_v049adamw8bit-annealing-_200wbwclaude_bs6_wd45-tmax175-TE-step00000335

Would it somehow be possible to simply replace the steps rather than the whole name, to run each new model--by steps?

Something like:
modelname-step00001000, ...1200, ...1400

Like in xy plot, with the S/R?

**Comment by mcmonkey4eva** [comment]
In the [Swarm](https://github.com/Stability-AI/StableSwarmUI) version of the interface, you can simply start typing the model name and then hit 'add all':
![image](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/assets/4000772/a51a0e69-fec3-48d8-b52d-49d237f54fd9)

In the auto webui version, iirc there's a fill button to spam all the model names, and then you can just delete the ones before & after your list. Bit more awkward but it works.

**Comment by rafstahelin** [comment]
@mcmonkey4eva gonna make a shell script to list models from a selection, will be super quick. Diving into the extension. Loving it
