### ISSUE TITLE
variables for output folder name

### ISSUE THREAD

**Issue by rafstahelin** [mcmonkeyprojects/sd-infinity-grid-generator-script#145]
would  be great to use variables to name the output folder like %Y%m%d%H%M%S etc
Also, if possible at all, to add within the the same field a subfolder path (in the output folder set in settings) like:
/grids/%Y%m%d%H%M%S
would help a lot organise with other outputs of the auto1111 suite
thanks

**Comment by mcmonkey4eva** [comment]
ftr the [Swarm](https://github.com/Stability-AI/StableSwarmUI) version of this has this built in as eg `grid-[date]-[time]` to have it auto-update to current date-time, supporting any of ` [date], [time], [year], [month], [day], [hour], [minute], [second`

so it'd indeed make sense to add to the auto version here too

**Comment by rafstahelin** [comment]
Got it. Though no one that I know uses it. But will look into it. Best of I can do all my prep and eval's in one place (comfyui). Thanks

**Comment by mcmonkey4eva** [comment]
if you already use comfy for things, you should definitely be using Swarm -- it's a wrapper around comfy that adds powertools like grids and a lot more

**Comment by rafstahelin** [comment]
I did not know that. How could I have missed it. Eager to look at it thanks
