### ISSUE TITLE
javascript required 

### ISSUE THREAD

**Issue by rafstahelin** [mcmonkeyprojects/sd-infinity-grid-generator-script#148]
I am running infinity grid generator on runpod jupyterlab. On windows i get the html page photo grid fine, but on jupyter the images dont show and get message about javascript. Unsure how to config to enable the images of the grid to show

![image](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/assets/64715158/7d809fcf-80c8-4fd5-866d-643534d70e9b)

**Comment by mcmonkey4eva** [comment]
That's a jupyter question -- the page uses javascript, you need to find out how to render with that enabled. Works fine loaded normally in a browser
