### ISSUE TITLE
feature request: navigation using arrow keys when viewing zoomed image

### ISSUE THREAD

**Issue by itswhateverman** [mcmonkeyprojects/sd-infinity-grid-generator-script#17]
It would be convenient if, when zoomed, you could use keyboard arrow keys or perhaps arrow buttons (on an overlay) to navigate to neighboring visible columns or rows. ESC key to close the zoomed overlay would be nice also.

Thanks!

**Comment by mcmonkey4eva** [comment]
Both parts added^
