### ISSUE TITLE
Bug: Hiding values seems broken on primary axes

### ISSUE THREAD

**Issue by itswhateverman** [mcmonkeyprojects/sd-infinity-grid-generator-script#19]
Since the inclusion of the super-axes (which are awesome, btw) there seems to be issues with hiding values through the advanced options. It appears axes with hidden values only work when displayed as super-axes.  If you hide a value on one of your primary axes, the grid doesn't update, nor does it update if you switch to an axis with hidden values.

**Comment by mcmonkey4eva** [comment]
Oops, yep, that was a small typo that completely broke hiding anything on the standard X axis. It's fixed now^
