### ISSUE TITLE
Feature request - Auto cycle 3rd axis

### ISSUE THREAD

**Issue by itswhateverman** [mcmonkeyprojects/sd-infinity-grid-generator-script#2]
This is a fantastic tool for comparison! Great work!

I think a good usability improvement would be to have the ability to auto-cycle through an axis of choice for comparison.

I would envision this as a check box and delay setting that could be applied to one of the axes such that while viewing 2 axes in the grid viewer it would swap values from the 3rd axis and auto-update the display.

For example: if I have model, steps, and cfg scale as my axes, and I'm actively viewing steps x cfg scale, I could check the box by model and set delay to 5 seconds to have my entire grid display cycle through each model while viewing without having to scroll up to change model and scroll back down to view.

**Comment by mcmonkey4eva** [comment]
So, first: this is a great idea, I just gotta figure out the code to make it work.

Second: I just want to note in regards to having to scroll around to change things - if you uncheck the "Show descriptions" box (if you use them), and check the "Auto-scale images" box, then zoom out (hold CTRL and mouse wheel down usually), you can usually get your grid images *and* the selector options on screen at once.

**Comment by mcmonkey4eva** [comment]
There's a button for that now!
Check the checkbox to enable them, then move the slider to the duration you prefer.

![](https://i.alexgoodwin.media/i/misc/5a3d15.png)

I credited you for this idea in the readme as well.

**Comment by itswhateverman** [comment]
Awesome, will check it out.  Great work!
