### ISSUE TITLE
generate html files before generating pictures

### ISSUE THREAD

**Issue by saaraahfar** [mcmonkeyprojects/sd-infinity-grid-generator-script#23]
I have this idea to generate html files before generating pictures for 2 reasons, 

1. we can open and compare when partial images generated 
2. we can easily replace html in case it was removed and alreted in anyway

what do you think?

**Comment by mcmonkey4eva** [comment]
Click the "dry run" checkbox in the UI, hit "Generate", then uncheck dry run and generate again.
When you do a dry run it'll output the HTML (as long as you don't uncheck the generate html option) but not generate images.
