### ISSUE TITLE
Recent WebUI has confusing issue about model

### ISSUE THREAD

**Issue by valconius** [mcmonkeyprojects/sd-infinity-grid-generator-script#25]
When generating anything (even when not changing model), the issue is:
```
Model loaded in 4.7s (0.5s create model, 3.6s load weights).
Error running process: /home/user/table-diffusion-webui/extensions/unprompted/scripts/unprompted.py
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/scripts.py", line 347, in process
    script.process(p, *script_args)
  File "/home/user/stable-diffusion-webui/extensions/unprompted/scripts/unprompted.py", line 218, in process
    setattr(p,att,Unprompted.shortcode_user_vars[att])
AttributeError: can't set attribute 'sd_model
```
The model loads just fine (although perhaps I should have tested that properly, maybe it isn't actually loading at all, I'm not sure because the models I was trying out looked very similar), in spite of the error claiming the contrary.

This same issue has appeared with numerous other extensions with recent webui commits. Perhaps it's related to the previous issue about the VAE https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/issues/24 in other words the webui API has probably changed a little bit.

**Comment by itswhateverman** [comment]
that error appears to be coming from the "unprompted" extension rather than infinity generator
