### ISSUE TITLE
[Feature request] Add field for folder name

### ISSUE THREAD

**Issue by acorderob** [mcmonkeyprojects/sd-infinity-grid-generator-script#27]
Creating the folder based on the template filename makes it impossible to make multiple grids from the same template without manually renaming or moving the folder. Adding an option to set the folder name (or at least adding something to the current folder name) would be great.

**Comment by mcmonkey4eva** [comment]
Good idea! There's now an option in the UI to specify any name you'd like (or leave it blank to use the default behavior of using the yaml filename).
