### ISSUE TITLE
Getting "AttributeError: module 'modules.hypernetworks.hypernetwork' has no attribute 'apply_strength'"

### ISSUE THREAD

**Issue by jonathangoorin** [mcmonkeyprojects/sd-infinity-grid-generator-script#31]
While using the latest Automatic1111 with 
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

getting AttributeError: module 'modules.hypernetworks.hypernetwork' has no attribute 'apply_strength'
every time i Try to run something

**Comment by mcmonkey4eva** [comment]
Sounds like your copy of the extension is out of date, that error was fixed in https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/commit/1d41ae79c62e32ce66e932165cad1e850b31647d

**Comment by jonathangoorin** [comment]
thanks!
