### ISSUE TITLE
How do I expand a 'Create in UI' grid?

### ISSUE THREAD

**Issue by Mistborn-First-Era** [mcmonkeyprojects/sd-infinity-grid-generator-script#32]
I used the 'Create in UI' feature to make an infinity grid. It is saved to an external drive if that matters. I was able to expand it the day I was creating it, however I would like to expand it further. I took a screenshot of all my settings and reconfigured them exactly the same (axis order, output folder name, prompt, and negative prompts). When I do a dry run to validate it it says it will make 0 images though. I tried to look for a yaml file for it but was unable to find one generated (do they auto generate?). My guess is that it has to do with the 'Select grid definition file' being set to 'Create in UI'. Is there a way to expand my old grid at this point?

**Comment by mcmonkey4eva** [comment]
Yes, you can still expand the grid, as long as you start from having all the same inputs - that includes axes too.
It's a little less convenient to reuse a grid made in UI vs. one made in YAML, but it works the same, you just have to refill the UI with the same inputs you had when you first made it, then add your new values into the list.
(Be careful with the seed too, happens to me way too often that i forget to specify a manual seed and rerunning a grid generates a different random seed and i have to start over)

**Comment by Mistborn-First-Era** [comment]
> Be careful with the seed too

Poop, that's why it's not working. 
Welp time to restart. I think it's time to write a yaml. 

Thank you for the quick and awesome extension!
