### ISSUE TITLE
multiple promptreplace

### ISSUE THREAD

**Issue by yggdrasil75** [mcmonkeyprojects/sd-infinity-grid-generator-script#34]
Unless I am doing something wrong, when I have 2+ valid promptreplace options, it only uses 1. I tried #18 which worked fine with 1 valid prompt, but when I have 2 or more, it stops processing after the last. I have a promptreplace axis setting a character, another setting a scene, with a second optional promptreplace if valid based on the first. only the second optional is used if both are valid. this was done with both using promptreplace instead of different spellings, but I do see 4 valid spelling options. does that affect it?

**Comment by mcmonkey4eva** [comment]
If you use `promptreplace:` twice in a single axis value, YAML can't parse that, which is why there's the trick to change the capitalization or the spaces.
`PromptReplace`, `Prompt replace`, etc. anything with different capitals or different spaces are all valid.

**Comment by yggdrasil75** [comment]
what about yaml arrays?

`promptreplace:
    - foliage=trees
    - color=green
    - backdrop=mountains`
or to better keep backwards compatibility, add promptreplacearray
