### ISSUE TITLE
Request: new mode - amount of seeds (variants)

### ISSUE THREAD

**Issue by Artemonim** [mcmonkeyprojects/sd-infinity-grid-generator-script#37]
### Problem
I need to experiment. I need a lot of variants with the same parameters. I'm too lazy to think about seeds.

~~Yes, I can choose `Seed` and input `-1, -1, -1, -1` for 4 variants, but why not to input just one number `4` cause I'm still lazy.~~
This method does not display real seed on the web page:
![2023-03-13_13-02-06](https://user-images.githubusercontent.com/36363466/224669480-c2c49b2f-3d95-4928-a055-f3671427d8d4.png)

### How it's may work
1. The user inputs one number of randomly generated seeds
2. The script itself generates as many random seeds as set by the user and inserts them into the further processing.

And it would be a good idea to automatically put the generated numbers in the input field and automatically change the mode to `Seed`, so that you can compare further results with those generated seeds.

**Comment by appleguy** [comment]
Is this different from just using Var Seed as one of the dimensions? That's what I've done, and it works quite well in my experience...sometimes I will set different Var Strength instead, since it can be helpful to have a gradient of different options to select one with just the right attributes.

**Comment by mcmonkey4eva** [comment]
You can do `1, 2, ..., 10` or similar as the seed input.

You can also do eg `1000, 1105, ..., 2000`  if you want high numbered seeds with big gaps or whatever.
