### ISSUE TITLE
Request: Axis navigation that's always accessible

### ISSUE THREAD

**Issue by Artemonim** [mcmonkeyprojects/sd-infinity-grid-generator-script#38]
### Request 
Axis navigation should stick to the top of the screen as well as the table header.
Right now, if you scroll down the page, you can't quickly change the third axis.
![2023-03-13_14-08-42](https://user-images.githubusercontent.com/36363466/224685831-4ae8e3a5-64ff-4fce-93e2-936139357965.png)

![2023-03-13_14-09-31](https://user-images.githubusercontent.com/36363466/224685818-bbbd0aad-41be-4b5b-9132-66c8672ff5ec.png)

### Optional
- A checkbox to disable sticking, because in some cases navigation can take up a lot of space on the screen.
- A triangle button for collapsing-expanding the navigation menu - quick access that can be quickly hidden.

**Comment by mcmonkey4eva** [comment]
There's now a checkbox for sticky nav (defaults off), and the nav is in an accordion.

Fun fact: having _two_ sticky things (the nav menu, and the table header) is apparently _not_ something HTML/CSS supports, at all. (You're expected to just shove them into the same container, which doesn't work here as one of them is part of a table, and the rest of the table can't be sticky). So... javascript hacks. Works, though the animation is not-so-smooth.
