### ISSUE TITLE
select subset of entries over active axes

### ISSUE THREAD

**Issue by piyarsquare** [mcmonkeyprojects/sd-infinity-grid-generator-script#4]
I generate images over a list of ~12 prompts and ~5 seeds over a range of models, scales, etc. When I have the prompt axis selected, it would be useful if I could view a subset of 4 or 5. I am not sure how it would integrate into the interface, but it would be great to have something you can select and reorder as needed. Then I might generate 50 prompts and 20 seeds if it is possible to view just a subset.

Thank you so much for this tool. Without any improvements, I find it to be incredibly useful and by far the nicest way to explore this space. Thank you very much for sharing your work.

**Comment by mcmonkey4eva** [comment]
Do you mean like, on the viewing page, a little checkbox on each value where if you uncheck it, it gets hidden from the output, to make it cleaner/simpler when you have a lot?

**Comment by piyarsquare** [comment]
Yes. Something like that, but I wouldn't want to clutter the interface. 
Would it be possible to have a dropdown with checkboxes like in an excel table?
Reordering would be an extra bonus.

**Comment by itswhateverman** [comment]
this is exactly what i was coming to suggest! I was thinking if values were hidden they could drop to the far right/bottom of list to stay out of the way but if its feasible the dropdown sounds cleaner

**Comment by mcmonkey4eva** [comment]
I added a new `Advanced Settings` dropdown to contain both the show/hide value toggle, and the pre-existing auto-cycle timer.
I think it works pretty smooth. Just unclick the checkbox for what you don't want to see, and it'll be gone. It's excluded from both the grid and the auto-cycle timer.

![](https://i.alexgoodwin.media/i/misc/67d4e5.png)
