### ISSUE TITLE
Unable to add new generations to the grid

### ISSUE THREAD

**Issue by Artemonim** [mcmonkeyprojects/sd-infinity-grid-generator-script#40]
### Problem
Let's say I have these axes:
`x-a`, `x-b`, `x-c`
`y-a`, `y-b`, `y-c`, `y-d`, `y-e`, `y-f`, `y-g`
`z-a`, `z-b`, `z-c`, `z-d`
`t-a`, `t-b`
So script will generate all the `x-a`, than all the `x-b`, than all the `x-c`.

And if you stop it on `x-b y-g z-d t-b` - you can start script again and it continue from `x-c y-a z-a t-a`
But, if you stop it on `x-b y-d z-b t-a` - the script will anyway start from `x-c y-a z-a t-a`

### Solution
The skipping algorithm must look at all levels, not just the first.

**Comment by Artemonim** [comment]
In addition, please also check if new variables can be added to the existing grid.
For example:
1. I generate grid with axis `style-a`, `style-b` and `style-c`
2. I also may change other axes
3. I remove `style-b` and add `style-d`
4. I regenerate grid with axis `style-a`, `style-c` and `style-d`

**Comment by mcmonkey4eva** [comment]
- Yes you can add new variables to each axis.
- The issue described in the opening post does not exist. It skips based on whether the image file exists already or not. It will render any images that haven't already been rendered.
