### ISSUE TITLE
Adding new axes removes previous generations

### ISSUE THREAD

**Issue by SMUsamaShah** [mcmonkeyprojects/sd-infinity-grid-generator-script#42]
1. Generate a page with 2 checkpoints/models.
2. Generate again but this time add another axes with 2 samplers.
3. Generations from step 1 are removed/replaced from the page.

Also I can add new axes but can not change or remove existing ones

**Comment by mcmonkey4eva** [comment]
You either
A: are working from the UI (as opposed to YAML) and didn't refill the old axis data when doing a new run, or
B: configured it properly but used a new folder name

-----

To recontinue a prior run, you must either
A: use a YAML file (so that the old axis config is still there) and just add new stuff to it, or
B: use the UI and fill out all axes exactly the same as they were before (or just don't close the webui page before generating again)

**Comment by SMUsamaShah** [comment]
> A: use a YAML file (so that the old axis config is still there) and just add new stuff to it, or

Does it mean that even if I use YAML, i can not change exisiting params? e.g. In second run if I want to use just one and a different seed (instead of previous 2 or more), its not possible?

**Comment by mcmonkey4eva** [comment]
I'm not sure what you mean.
I can tell you you can do basically whatever you need to do, the question is just *how* to do it properly.

As to *how*, it depends on what you mean.
If for example you want to change the value of a specific parameter within an axis and redo the run, but keeping the existing generations for all the others, via YAML, you can just add a new parameter and delete the old one, making sure the key is different.

If you want to generate an even smaller subset of changes, you can either
(A) delete the existing images you want redone so only those get reran, or
(B) use YAML and set "skip: true" on every parameter you don't want to rerun, and run with "overwrite existing images" checked.

If neither of those are what you're asking, please try to clarify what you mean.

**Comment by SMUsamaShah** [comment]
Lets say we do:
- 2 samplers (euler, ddim)
- 1 prompt (tree)
- 2 seeds (1, 2)

after this I want to update the grid with different and less parameters this time
- 1 sampler (dpm2)
- 1 prompt (flower)
- 1 seed (5)

can i do this while still keeping all results from first run in the grid?

**Comment by mcmonkey4eva** [comment]
Yes - just *add them*.
As in, keep your old parameters in place. They will not be regenerated unless you enable "Overwrite existing images".

If you want to prevent crossing over (eg you don't want to generate `dpm2 + tree`) you can use the YAML file mode and add `skip: true` to all params you don't want running at all.
