### ISSUE TITLE
request: time taken

### ISSUE THREAD

**Issue by yggdrasil75** [mcmonkeyprojects/sd-infinity-grid-generator-script#46]
I would like to be able to know how slow a particular model or sampler is. some models are really slow and produce good art, but some are really fast and are not much worse. some samplers are really fast and amazing but on some models those samplers produce trash. a way to add automatically in a model and description the average time taken would make picking a new combination easier. in addition, average time for each column/row shown would be nice.

**Comment by mcmonkey4eva** [comment]
Models should not have different speeds to each other, ever.
Samplers do have different speeds, but it's mostly uniform with most samplers being _roughly_ the same speed and a couple being half that speed.
Either way, measuring generation time seems separate from the goals of this extension.

**Comment by mcmonkey4eva** [comment]
It will *load* faster but it will not generate faster. At generation time all models will be in the same format (non-EMA weights from an unpruned model will be ignored, half vs. non-half will be automatically forced to whichever GPU precision target you have selected (which is half by default)). There's no compression either way.
