### ISSUE TITLE
feature request: pop over/out zoom

### ISSUE THREAD

**Issue by itswhateverman** [mcmonkeyprojects/sd-infinity-grid-generator-script#5]
It would be nice if individual images were clickable for either a zoomed overlay or pop out window.

**Comment by mcmonkey4eva** [comment]
So, first: personally I'm of the mind to just Right Click -> `Open Image In New Tab` to view an individual image like that.
But I'm not going to force other people to follow my preference, and you're definitely not alone in wanting the click to view fullscreen thing - not to mention the potential for use with #6.

So, added. Once you update and run the webpage gen again, it will let you click any image, and it will pop up to fill 90% of screen space. Simply click outside of the image itself to close that popup. Also has display text of the image URL (which contains the selected generation IDs) at the bottom, as a placeholder for where more metadata can go in the future.
