### ISSUE TITLE
filecache not ram cache (or optional cache)

### ISSUE THREAD

**Issue by yggdrasil75** [mcmonkeyprojects/sd-infinity-grid-generator-script#51]
when you get a few million variations on your megagrid, let it run through the night and the next day, because this script caches the images to allow the webpage to load faster, it gets to be massive. just checked my ram this evening after work, of my 96 gb of ram, I was using 350 gb (pagefile of course), this meant I couldnt do anything.
also, at that amount of variations, it takes nearly 2 hours to start the script. make the webpage caching optional, as I just access from the file directly, and have the cache builder write a json array of all the prompts to a file so that as long as the yaml isnt modified, the json can be fed directly into the api after it is made and no extra startup time is needed (hash the yaml)

**Comment by mcmonkey4eva** [comment]
No part of this script does any form of image caching.

If it did, even The MegaGrid, which has 445k images in it and took around a full week together to render, only takes 5.2 GiB on disk, and so if it were cached would only occupy 5.2 GiB of RAM, not 350 GiB.

The situation you described is not only not accurate to how anything works (there is no cache in the script), the numbers extra so make no sense (you cannot possibly generate 350 gig of memory from SD in a human duration of time, it would take months if not years on high end hardware).

**Comment by yggdrasil75** [comment]
@mcmonkey4eva 
![image](https://user-images.githubusercontent.com/17131496/228085698-fd5ad54d-48d8-4a3d-b47e-337bf91f430a.png)
this is roughly 2 minutes after hitting the start button. do you know if stable diffusion reserves memory for each image it will generate? because idle stable diffusion uses around 50 mb, and it is only after starting the generate that this happens. it continues to climb as it goes, but I had to restart it due to the aforementioned massive memory leak. since I took that screenshot, it has climbed another 10 gb as I sit here being a slow typer.

**Comment by yggdrasil75** [comment]
![image](https://user-images.githubusercontent.com/17131496/228086342-074b22c1-da80-4353-a65b-e19f5b59f454.png)
another few minutes later. still climbing. I will note that my yaml does have a few too many variations 
![image](https://user-images.githubusercontent.com/17131496/228086422-c3fb3088-c216-4488-8741-c2b3f1b3f099.png)
but something is being done incorrectly. either here with generation of the queue or with a1111 with inserting the new image to the queue.

**Comment by yggdrasil75** [comment]
![image](https://user-images.githubusercontent.com/17131496/228096731-f9543d4e-06e5-4535-9ffb-b88ca882c390.png)
actual number being generated is around 4 million. I just have those prompts there because they are ideas I want to test but doubt I will ever get to unless I rent a server farm. I know that even 4 million will not be done any time soon, I just generate every once in a while. it still takes upwards of an hour to get to that point though where I can even see the total number to be generated.
overall: the generation params should be cached in pycache as a json or something so that startup time and background ram usage can be reduced.

**Comment by mcmonkey4eva** [comment]
There's a button in the UI for if you care about load time for large runs

![image](https://user-images.githubusercontent.com/4000772/228106030-1712d28b-d0be-4a2b-b3b3-9bf994128d82.png)

Note that 4 million is still a huge amount. At one image per second that will take over a month to complete.

You can expect up to maybe around a kilobyte or two per target generation of RAM usage, so for 4 million images queued up expect around 4-8 GiB of RAM to be taken. This of course can be reduced by not running a month worth's of image generations all in one go.
