### ISSUE TITLE
Request: autoupdate image once generated

### ISSUE THREAD

**Issue by nonnull-ca** [mcmonkeyprojects/sd-infinity-grid-generator-script#58]
Is it possible to autoupdate images in the browser once they are generated?

You can manually force an update by clicking on any axis selector, but this requires scrolling to the top which is annoying on larger grids.

For now I am doing the workaround of running:

```
go = 1; function FillTableForever() { fillTable(); if (go) {setTimeout(FillTableForever, 10000);}}; FillTableForever()
```
in the browser console, but this:

1. Is annoying, as I have to execute said script.
2. Is polling-based, and somewhat hammers the server as a result.
3. Partially resets browser state when run.
4. Has a relayout for a moment, even if no images changed.

I realize currently that the generation is largely decoupled from the serving of the resulting directory, which makes true pushing rather difficult. That being said, something along the lines of the following could work:

1. Generation script maintains a `recent.csv` file in the output directory:
    1. Said file has say, 10 lines of "sequence_num, path_to_file"
        1. Tradeoff here between small file -> less data polled and large file -> less frequently missed updates.
    3. Generation script updates said file after every file generated.
        1. This update needs to be atomic, by e.g. using [atomicfile](https://pypi.org/project/atomicfile/).
4. Browser polls said `recent.csv` frequently:
    1. If file changed:
        1. If we potentially missed an update (min sequence # in new file is not present in old file), do a full refetch:
            1. For all images:
                1. Initiate a refetch of the image.
                3. When complete, replace the image with the refetched image
        1. Otherwise, for all files changed:
                1. Initiate a refetch of the image.
                2. When complete, replace the image with the refetched image

**Comment by mcmonkey4eva** [comment]
added!
