### ISSUE TITLE
Bug: Windows folder path limit

### ISSUE THREAD

**Issue by mjcampbel** [mcmonkeyprojects/sd-infinity-grid-generator-script#59]
I had images stop showing up on the webpage as I added more axes in the yaml and I think I've figured out why. They are all being created and sorted into the correct folders, and the webpage is looking in the correct place, but I was getting placeholders in a lot of spots. 

After some troubleshooting it looks like I hit the maximum character limit for a file path in windows at 260 characters. I tested it by generating a file path of 259 characters, I confirmed that the webpage loaded the image, then added a character to axes: Test: values: 1234(5) and the image stopped loading. 

I'm pretty sure this can't be fixed, since it's a windows issue, but maybe get an alert if the file path gets over a certain limit

**Comment by mcmonkey4eva** [comment]
This is actually pretty easy to fix on modern Windows: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html ... kinda weird that it's not allowed by default still.

**Comment by mjcampbel** [comment]
Wow, is there anything a little regedit tweaking can't fix? Thanks for the tip, now to continue adding far more axes than I'll ever need

**Comment by mcmonkey4eva** [comment]
(Keeping this open as a feature request to detect and add a notice about it for future users)

**Comment by mcmonkey4eva** [comment]
There's now a detection + console message for it
