### ISSUE TITLE
Request: Option to prevent to start process if infinite-grid webviewer page already exists

### ISSUE THREAD

**Issue by Filexor** [mcmonkeyprojects/sd-infinity-grid-generator-script#60]
Currently, we have "Overwrite existing images (for updating grids)" option to prevent images being overwritten.
However, this is not suffice to prevent assets for infinite-grid webviewer page being overwritten or processed images being saved in new folder.

These can be avoided by checking there is no assets in output path and nothing in output path/images .

**Comment by mcmonkey4eva** [comment]
Do you mean that you accidentally created a new grid into a folder name that you've used previously? If so yeah I can definitely add a check for that, probably in the form of a little red "That already exists!" notice rather than a checkbox.

**Comment by mcmonkey4eva** [comment]
Added
