### ISSUE TITLE
Resuming/batching a huge grid

### ISSUE THREAD

**Issue by Chubbly** [mcmonkeyprojects/sd-infinity-grid-generator-script#62]
I'm not sure if this is a feature or a help request but here goes:

I started a large job generating 7920 images, thinking that it would maybe be done overnight. However, it has now been overnight and it is only 10% of the way through. 2 questions then:

1. Can I resume a job using the the same yaml file/folder if I terminate the server process?
2. Using the Dry Run functionality, can I generate a monster grid with all my axes defined and then break it down into stages by toggling axes using the `skip: true` flag? It may take a week but it means that I can mess around with other jobs during the day and then resume the mega job overnight. Is this possible and have I understood the `skip: true` functionality correctly?

Thank you for the amazing extension, it is really helpful understanding how lots of different parts can affect image generation!

**Comment by mcmonkey4eva** [comment]
Yes you can stop/resume freely.

Yes you can skip things you don't want to run yet and run those later. Note that you skip _values_ within an axis, not an entire axis.

Note also that grid size is exponential, so eg if you have ten axes, and have one axis with 5 values, and you skip 4 of the values within just that axis without touching the other axes, the run will take 1/5th the total time.
