### ISSUE TITLE
Prompt replacer with multiple terms

### ISSUE THREAD

**Issue by Corgano** [mcmonkeyprojects/sd-infinity-grid-generator-script#66]
I'm trying to use the Prompt Replacement feature to iterate through multiple poses, however Im racking my brain how to have it replaced one term with multiple terms

For instance I can have a prompt `masterpeice, well drawn, cat ears, cat girl, holding itemhere` and have it replaced item here with one thing easily
`Itemhere=apples, itemhere=a harpoon, itemhere=her tits`
The result is as you expect, 3 images with the anime girl holding the 3 different items

The issue is in some replacements, you want to replace with a set of terms. Same prompt, consider the following replacements
`itemhere=apples, itemhere=(a harpoon, scuba mask, flippers), itemhere=(her friends tits, couple, duo, embarrassed)`
Given the item being held there are additional terms that also make sense to be included, but in other cases no additional terms are desired. 

Right now it breaks it at EVERY comma, garbling the intended result. Ideally there would be a way to escape the commas so that they are not broken apart when being used as a replacement string, but also replaced by regular commas when being included in the end prompt. I can't find a way to do this and even tried adding in my own solution (adding a line to convert a different symbol like ; into , when doing the replacement) but nothing I try works. Any ideas?

**Comment by mcmonkey4eva** [comment]
use `||` instead of `,`.

if `||` is present, commas are ignored.

**Comment by Corgano** [comment]
Thank You so much! It would be fantastic if this was added in the
documentation in the info next to the prompt replacement feature,
completely missed it.
