### ISSUE TITLE
Request: A .yaml sharing community

### ISSUE THREAD

**Issue by vis223** [mcmonkeyprojects/sd-infinity-grid-generator-script#67]
Unless I'm missing something these .yaml files would be great to share between  users.
 Certainly those involving built-in extensions.  It'd be great to explore some of the creative ways people are using this. 
 Does such a forum exist already?   Similar to the way embedding files are shared?

**Comment by mcmonkey4eva** [comment]
I'm not aware of any general sharing forum for them, though I have seen some posted from time to time in random discords n wotnot. I've enabled the [Discussions](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/discussions) tab here which would be a nice place to post any you'd like to share.
