### ISSUE TITLE
display and escape grid prompt and prompt replace labels

### ISSUE THREAD

**Issue by emileswain** [mcmonkeyprojects/sd-infinity-grid-generator-script#68]
Will see if i can do a PR, but in the mean time, i've noticed that when viewing the grid it would help if we could see the actual full prompt rather than the key for it. 

Also, we were testing the effect of having prompts where we'd trained a model with `<mystyle>` and this isn't escaped in the grid view, so you don't actual see the replacement prompt as its treated as html.

**Comment by mcmonkey4eva** [comment]
Html escaping: replicated and fixed, thank you for the report. (Note that users emitting HTML is an intended feature, but of course it's not meant to happen from simple parameter text as happened here)

For viewing the full prompt after a prompt replace, you can click an image to see that image's unique metadata.
Implementing that directly in the grid itself would have two issues:
A: Long prompts would be a mess. I've had fun generating grids with `Prompt` as an axis, formatting gets wonky when that's huge.
B: If you have multiple `prompt replace` keys on axes, I don't know that there'd be a sane way to render that. There'd be two different "full prompts" visible and you'd have to guess which is the "real" one.

Let me know if being able to click to view is insufficient for you, and you have an idea for how it handle it well in a way that avoids the issues above.
