### ISSUE TITLE
cycle with keyboard arrows?

### ISSUE THREAD

**Issue by piyarsquare** [mcmonkeyprojects/sd-infinity-grid-generator-script#7]
This is an amazing extension. Super useful. And I am very grateful for your support and useful updates. (If I say these things just before making a request, does it seem disingenuous?)

Now that I have seen the auto-cycler, I want to control it with my keyboard instead of waiting for the specified amount of time. Is that possible? Say with the forward and back arrows?

At present, there is only one set I would want to cycle through (models or prompts), but I could imagine using different key-pairs to more forward and backward through different axes.

Again, love the tool and thank you so much!

**Comment by mcmonkey4eva** [comment]
There's already keyboard movements built in, they just weren't updating properly it seems unless you hit 'Enter' - with the commit above, it now updates the grid as you go.

I think I can do better than that though.

**Comment by mcmonkey4eva** [comment]
And indeed I can :D

On the new build up/down move between axes, left/right move between values.
You'll have to click any of the tabs first to have it focused to use arrow keys.
There's a yellow highlight on the focused tab to make it easier to tell on Chromium browsers (Firefox has its own focus highlight built in)

It also automatically compensates for hidden values and things like that.

If auto-cycle overwrites your selection it will lose focus and you'll have to click back in.

**Comment by kuso-ge** [comment]
@mcmonkey4eva  Hi, it's me again. Anyway to have this feature without having the focus scrolling on the input tabs? 

Right now, every time I navigate the tabs to change the previewed images, it always scrolls back to the tabs. 
![Untitled video - Made with Clipchamp](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/assets/12083007/730b7a03-f500-4642-beea-eacd6243ee4c)

something like:

```
#psuedo code
element.focus({
  preventScroll: true
});
```

**Comment by mcmonkey4eva** [comment]
That is the largest grid header I have ever seen.

**Comment by mcmonkey4eva** [comment]
Done, works great in testing!
