### ISSUE TITLE
Generated HTML does network access to fonts.googleapis.com

### ISSUE THREAD

**Issue by skfoo** [mcmonkeyprojects/sd-infinity-grid-generator-script#75]
The bootstrap.min.css imports stuff from fonts.googleapis.com. I realize it's not a big deal but I was surprised it was doing network access when I didn't expect any.

**Comment by mcmonkey4eva** [comment]
Oh, yeah, that's gross. I removed it. The font is very slightly different now but -barely-. Thank you!
