### ISSUE TITLE
Update only an axis without regenerating everything? 

### ISSUE THREAD

**Issue by kuso-ge** [mcmonkeyprojects/sd-infinity-grid-generator-script#79]
Anyway to update an axis or some selected axes without having to regenerate the entire grid? 
My generation time is like 28 hours, different models on different LORA's, in different settings. It's taking a while and when a LORA is updated, I have to regenerate the entire thing.

**Comment by mcmonkey4eva** [comment]
If you're not already using YAML inputs, there's a YAML file output to the generation folder, which you can then copy into the extension's `assets` dir as a starting point, though you'll need to check the readme's guide to YAML files either way.

With a YAML file, you can set some values to `skip: true` to indicate that they should not be regenerated - you'd then set every value in your lora list to skip other than the one you want to redo, check Overwrite in the UI, and run grid gen for that yaml.

Alternately, if you're planning in advance, you can set the thing that changes a lot (your lora list) to be the topmost axis, so then you can just delete the folder you want to redo and thus save the rest of the trouble, just disable overwrite and run as normal.
