### ISSUE TITLE
Prompt Search and Replace doesn't understand putting things in quotes, resulting in the inability to replace sections of a prompt

### ISSUE THREAD

**Issue by Jellybit** [mcmonkeyprojects/sd-infinity-grid-generator-script#81]
1. Create a prompt that says:
`A horse fights a cat, large robot in the background, photorealistic`
2. In the infinity grid script, set the first axis to seed, and put in two numbers like so:
`1701, 8675309`
3. In the next axis, choose Prompt Replace, and put the following in the input, just as you would with XYZ Plot:
`"cat, large robot in the background, photorealistic", "dog, small pig in the foreground, photorealistic", "cat, cartoon, 8K, Artstation, perfect texture"`

In XYZ plot, it would replace the first line in quotes with the second line in quotes, and so on. In Infinity Grid, if you do this, it will say it can't find the text. XYZ Plot puts in this capability, because text can include commas, and can in fact have elaborate differences. I could just write completely different prompts, but it can be hard to pick out the changes I've already done when a list gets long enough, where with search and replace, I know the exact changes I made, and can read them all quickly in a list.

**Comment by mcmonkey4eva** [comment]
The syntax to avoid breaking when replacing commas is `||`
So eg `cat, large robot in the background, photorealistic || dog, small pig in the foreground, photorealistic || cat, cartoon, 8K, Artstation, perfect texture`
