### ISSUE TITLE
Auto-scale images to viewport width includes hidden items in calculations

### ISSUE THREAD

**Issue by skfoo** [mcmonkeyprojects/sd-infinity-grid-generator-script#85]
Using advanced options you can hide axis values. So if an axis has 10 items and you hide half of them, when you turn on autoscale it should calculate stuff to fit 5 images. However, it uses all 10 items in the axis in the calculation, which makes the resulting images too small.

**Comment by mcmonkey4eva** [comment]
Handled by #86
