### ISSUE TITLE
Request: Ability to prompt replace, starting with an empty value

### ISSUE THREAD

**Issue by DrTinyFace** [mcmonkeyprojects/sd-infinity-grid-generator-script#89]
I've run into a bit of an issue with my prompting, and I'm not sure if it's because I've overlooked something or if the feature just isn't there. Basically instead of replacing a section of a prompt right from the start, I'd like to be able to have an empty value to start and then "replace" that empty value with other values later on.

I'll use the example I'm having issues with. I want to be able to have a character generate, then start swapping out parts. So for example, in the first image I want her to be just a normal human, and in the second I'd like to give her a robot arm, then in the third robot wings (removing the robot arm). The way I'm working around it right now is just making up a completely nonsense word (in my case, anatopolis) and then using the replace prompt to replace that word in future generations (mechanical arms for the second generation, mechanical wings for the third). Is there a way to change it so that instead of doing "anatopolis, mechanical arms, mechanical wings", I could do something more akin to "(blank), mechanical arms, mechanical wings"?

Main reason I'm asking for this is so that the people who use my AI (friends and family who aren't as computer savvy and also can't directly edit the .ymls) don't have to also put in some default prompt to get the infinity grid working. I want them to be able to just say something like "1girl, red hair, from above" and choose my .yml to have it generate the three prompts.

Thank you a ton for reading this admittedly long winded request, and I hope this is something that I'm either just missing or could be added :)

**Comment by DrTinyFace** [comment]
Changed the name, since the other was vague lol

**Comment by mcmonkey4eva** [comment]
This sounds more like a case to use _styles_? Styles are a dropdown box in the webui that does this for non-grid usage (append custom premade text to the prompt), which you can also use as a grid input if you reference them by name.

**Comment by DrTinyFace** [comment]
Styles would be a better workaround for this than what I've been doing, but I definitely think it would be more convenient to have an option to just add from a default blank text without having to clutter your styles with (potentially) hundreds of prompts. That being said, I'm personally happy to use styles since I don't use them for anything else right now, so no skin off my back if you don't add that, but I could see the argument for adding it. Either way, thank you for this excellent plugin and I appreciate the work you've already put into it :)
