### ISSUE TITLE
Click to Popup broken recently?

### ISSUE THREAD

**Issue by brendanhoar** [mcmonkeyprojects/sd-infinity-grid-generator-script#91]
I noticed that clicking on an image did not show the popup. Looks like it needs just a small change.

I've created a PR here:

https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pull/90

B

**Comment by kuso-ge** [comment]
It works on my end though

**Comment by mcmonkey4eva** [comment]
Valid bug, good fix PR, thank you!
