### ISSUE TITLE
Update Automatic's state.job_count with the total number of images to get a proper progress bar

### ISSUE THREAD

**Issue by skfoo** [mcmonkeyprojects/sd-infinity-grid-generator-script#92]
The script isn't updating the job count with the total number of images it generates, so Auto1 only shows progress for the first image generated. To fix this you just have to edit two lines in infinity_grid.py,

1. Import the state object from modules.shared: `from modules.shared import opts, state`
2. In a1111_grid_runner_pre_run_hook, set the job count: `state.job_count = grid_runner.total_run`

Edit: I found that the total step count didn't include hires steps, and also that Automatic was overriding the value we give it, so I made a PR. The total progress bar should be correct now.

**Comment by mcmonkey4eva** [comment]
#93 pulled
