### ISSUE TITLE
Request: Better display of prompt replace values

### ISSUE THREAD

**Issue by alinsavix** [mcmonkeyprojects/sd-infinity-grid-generator-script#94]
Howdy! Lovely tool you've made here. <3

One thing I noticed while using it, that's kind of irritating, is the way the columns are labelled for prompt replace rules. It ends up displaying both the original prompt and the replacement prompt _for every single replacement_, and since the source prompt doesn't change, this just ends up repeating the same information over and over again, taking up tons of extra space when it's just not needed.

It would be great if there was at least an option to only use the replacement string as the value to display in the completed html, so I can get some space and readability back.

**Comment by mcmonkey4eva** [comment]
now displays how you'd probably expect
