### ISSUE TITLE
bug: cannot remove axis mode

### ISSUE THREAD

**Issue by rjgoif** [mcmonkeyprojects/sd-infinity-grid-generator-script#95]
If I set 3 axis modes but later want to go back to 2 axis modes, I cannot "uncheck" the third mode. Clicking on the option again doesn't uncheck it, and deleting the text on the dropdown and hitting enter just re-selects it. 

Only current solutions: 
- refresh Automatic1111 to clear all settings, or
- edit the yaml file, save it, then make a grid referencing the yaml file rather than the UI.

**Comment by mcmonkey4eva** [comment]
at the very top of the mode list, there is an empty entry - select that to disable the axis.

**Comment by rjgoif** [comment]
Ha I am sorry, I fee like a fool. I couldn't see it because it was the same color as another bar it was overlapping on the UI and it blended in perfectly. Sorry to bother you with a silly bug report.
