### ISSUE TITLE
Feature request: change order of axis values

### ISSUE THREAD

**Issue by rjgoif** [mcmonkeyprojects/sd-infinity-grid-generator-script#98]
This would be a huge one for model comparisons: 

When exploring how to train a model, a lot of variants can be explored independantly (e.g. training image sets, steps, network alpha, schedulers, etc.) and it's great to compare results side by side in a particular order. 
However, this order may not reflect the order of the initial grid construction, and might change by which comparisons you want to make.

It would be extremely useful to be able to re-order the values of an axis in a pre-existing grid.

This way, you could build a master grid of your models as you train them, comparing them pair wise or in lists as needed on the fly. 

Not sure if this is would be easy, but worth a shot asking.

**Comment by mcmonkey4eva** [comment]
That's easy to do if you use the full-fat YAML input format (which you should be doing if you're building a master grid with updates over time)
